import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import process = require("process");
import { cn } from "../lib/utils";
import Sidebar from "./Sidebar";
import Home from "./page";
import { LeftNav } from "./LeftNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:{
    absolute: "",
    default : "One Vega Dashboard",
    template: "%s | OneVega"
  }, 
  description: "Generated by create next app",
};
// const Menu = [{
//   label: "Prompts",
//   id: 1,
//   url: "/prompts"
// }, {
//   label: "Bcf Boards",
//   id: 2,
//   url: "/boards"
// }]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(" bg-dark text-light", inter.className, { 'debug-screens': process.env.NODE_ENV == "development" })}>
        <div className="w-full flex min-h-screen w-full">

           <div className="sidebar border-r w-60 ">
            <LeftNav />
          </div> 
          <div className="MainSec p-5  w-full">
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
